/**
 * DO NOT UPDATE THIS FILE MANUALLY!!!
 *
 * This file has been automatically generated by `scripts/add-boilerplate.js`.
 * If you want to add a new boilerplate, please run command bellow and follow the instructions 🙏
 *
 * ```
 * pnpm run boilerplate:add
 * ```
 */
import nodeCliBoilerplate from './node-cli-boilerplate/index.js';
import reactMinimalBoilerplate from './react-minimal-boilerplate/index.js';
import reactMonorepoBoilerplate from './react-monorepo-boilerplate/index.js';
import reactNostalgiaBoilerplate from './react-nostalgia-boilerplate/index.js';
import reactUiBoilerplate from './react-ui-boilerplate/index.js';

export default [
	nodeCliBoilerplate,
	reactMinimalBoilerplate,
	reactMonorepoBoilerplate,
	reactNostalgiaBoilerplate,
	reactUiBoilerplate,
];
