/**
 * DO NOT UPDATE THIS FILE MANUALLY!!!
 *
 * This file has been automatically generated by `scripts/add-boilerplate.js`.
 * If you want to add a new boilerplate, please run command bellow and follow the instructions 🙏
 *
 * ```
 * pnpm run boilerplate:add
 * ```
 */
import reactMonorepoBoilerplate from './react-monorepo-boilerplate/index.js';
import reactNostalgiaBoilerplate from './react-nostalgia-boilerplate/index.js';
import reactUiBoilerplate from './react-ui-boilerplate/index.js';

export default [
	reactNostalgiaBoilerplate,
	reactMonorepoBoilerplate,
	reactUiBoilerplate,
];
